name: Build and Test
on: [push]

jobs:
  bat:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Perform npm tasks
        run: npm run ci
      - uses: actions/upload-artifact@v3
        with:
          name: built-action
          path: |
            **/*
            !node_modules/

  integ:
    needs: bat
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: macos-latest
            release: latest
          - os:  ubuntu-18.04
            release: latest
          - os: ubuntu-latest
            release: latest
          - os: windows-latest
            release: latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: built-action
      - name: Perform 'setup-matlab'
        uses: ./
        env:
          MATHWORKS_MATLAB_BATCH_BASE_URL: https://mw-ci-static-dev.s3.amazonaws.com/matlab-batch/v1
        with:
          release: ${{ matrix.release }}
      - name: Run MATLAB Command
        uses: matlab-actions/run-command@v1
        with:
          command: license inuse
